### ISSUE TITLE
Questions: mDNS reflector

### ISSUE THREAD

**Issue by edenhaus** [hmmbob/HomeAssistantConfig#2]
Hi,

in https://github.com/home-assistant/core/issues/48615#issuecomment-812447332 you commented, that you use a mDNS reflector. As my setup is similar to yours (with core, traefik and co), I want to ask you to share some information about the mDNS reflector.
My setup currently does not support zeroconf, but it would be a nice to have feature.
Can you please give me some information about it (which reflector you are using and how)?

Thanks in advance

**Comment by hmmbob** [comment]
Sorry, missed this issue :)

I believe it was as easy as installing `avahi-daemon` on my Debian host machine, and editing `/etc/avahi/avahi-daemon.conf` so that the following was uncommented (I have it at line 57-58):

```
[reflector]
enable-reflector=yes
```
It was the only change I made. Restart avahi and see if it works :)
Without checking, something like this should get you there:

```bash
sudo apt-get update && sudo apt-get install avahi-daemon -y
sudo nano /etc/avahi/avahi-daemon.conf

# edit the file as per above, ctrl-x and Y to save

sudo systemctl reload avahi-daemon
```

**Comment by hmmbob** [comment]
I know that there are also Docker containers around that do the same. I chose to do this on my host, vs in a container. You might want to have a look at those solutions too and see what works best for you.

**Comment by edenhaus** [comment]
Thanks :) I will test it the next days
